### PR TITLE
fixed minor typo where the "GLUNIFORM2FVFN" extension had been used where it wasn't intended

### PR DESCRIPTION
**Pull request by d4v3y5c0n3s**
Previously, "GLUNIFORM2FVFN" had been used where "GLUNIFORM3FVFN" and "GLUNIFORM3FVFN" should have been used instead on lines 148 & 149.

### CODE REVIEW

**Comment by d4v3y5c0n3s** [comment]
Also, quickly compiled the engine with the changes and encountered no errors.  I will test compiling the demos and report whether they also work with the changes or not.

**Comment by d4v3y5c0n3s** [comment]
Oops, accidentally closed it there.  My bad.

**Comment by d4v3y5c0n3s** [comment]
In order to test the demos I think that I need to add libcorange to my path.  I'll do that later unless you test the demos first.  Hopefully this minor fix will get merged. :)

**Comment by orangeduck** [comment]
Thanks a lot. Looks like a copy-paste error so I'm sure it will be fine without testing the demos.

**Pull request merged**
