### PR TITLE
Little Fix folder_unload() + SSAO artefacts fix + Shadow fix

### PR DESCRIPTION
**Pull request by fedor-elizarov**
folder_reload not work becouse folder_unload not unload files becouse not have slash :D

### CODE REVIEW

**Comment by fedor-elizarov** [comment]
SSAO artefast on Radeon HD 6850 free radeon (mesa+gallium) driver, Perhaps there is no such problem on other video cards.

**Comment by fedor-elizarov** [comment]
Shadows:
if in `graphics.cfg` set `shadows=0` and lighting=1 

The image is heavily obscured, I have not found a better way out, how to clear the shadows and do the calculations always, it is slower, but I do not know how to do otherwise.

**Comment by fedor-elizarov** [comment]
Check the code, maybe I went wrong with the solution. :upside_down_face:

**Comment by orangeduck** [comment]
Looks great, thanks a lot!

**Pull request merged**
